### ISSUE TITLE
Elm-assisted unit-test generation

### ISSUE THREAD

**Issue by netaisllc** [elm-lang/projects#8]
Someone else is already there in JS-land, but maybe this would have appeal to Elmers.
### SpeckJS

> Write vanilla comments that automagically convert into full test spec files.

The philosophy seems in tune with Elm...

> Our goal with SpeckJS is to make it as easy as possible to get started using Test-Driven Development on a new project, to quickly add unit-tests to your existing project, or anywhere in between. We know the value of well-tested code, and SpeckJS is here to make that simpler than ever.

[repo](https://github.com/speckjs/speckjs)

PS. I am not affiliated nor advocating.

**Comment by kmarekspartz** [comment]
You may be interested in elm-check, a property-based testing framework for Elm:

https://github.com/TheSeamau5/elm-check

Property-based testing is similar to what you describe, though what you link to is more of a doctest-oriented approach...

**Comment by evancz** [comment]
This seems like an interesting idea. There's a version of this in typed functional languages is called [Liquid Haskell](http://goto.ucsd.edu/~rjhala/liquid/haskell/blog/about/) so that'd be interesting to explore as well.

I don't really want to add this to this repo. I don't know this domain well enough to clearly define the project for this page. Maybe if there's a nice PR at the bottom of all the projects, but otherwise I am not realistically going to write this up.
